# Generated by Django 6.0.6 on 2026-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module', models.CharField(choices=[('APPARATUS', 'Apparatus'), ('ENGINEERING', 'Engineering'), ('TECHNICAL', 'Technical'), ('INVENTORY', 'Inventory'), ('FINANCE', 'Finance')], max_length=50)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
