# Generated by Django 6.0.6 on 2026-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('TESTING', 'Testing'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('SOP', 'SOP')], max_length=50)),
                ('linked_project', models.CharField(max_length=200)),
                ('linked_apparatus', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('file', models.FileField(upload_to='technical_reports/')),
            ],
        ),
    ]
