# Generated by Django 6.0.6 on 2026-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('linked_module', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
