# Generated by Django 6.0.6 on 2026-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=200)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linked_apparatus', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
