# Generated by Django 6.0.6 on 2026-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('linked_apparatus', models.CharField(max_length=200)),
                ('linked_inventory_item', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
